/**
 * Demo içeriği — yalnızca geliştirme ve deneme için (prisma/seed.ts kullanır).
 * Kişiler kurgusaldır; e-postalar örnek alan adındadır.
 *
 * Kayıtlar konu şablonlarından üretilir: her konunun 2 başlık ve 2 açıklama
 * biçimi var, böylece aynı konu en fazla 4 farklı kayıt olarak görünür.
 * Konular ünitenin kendi sözcükleriyle yazıldı (ör. Kalite Güvence: sapma,
 * seri serbest bırakma, GMP) — ML ekip önerisi bu ayrışmayı öğrenir.
 */
import { Role } from '../src/domain/enums.js';

export interface DemoUser {
  /** Kalıcı anahtar — kullanıcı satırı `seed:<key>` Entra yer tutucusuyla bulunur. */
  key: string;
  name: string;
  dept: string | null;
  role: Role;
}

export const USERS: DemoUser[] = [
  { key: 'u1', name: 'Ömer Uygun', dept: 'ik', role: Role.TEAM_MEMBER },
  { key: 'u2', name: 'Ayşe Kaya', dept: 'ik', role: Role.TEAM_MEMBER },
  { key: 'u3', name: 'Mehmet Demir', dept: 'ik', role: Role.MANAGER },
  { key: 'u4', name: 'Melda Yalçın', dept: 'ik', role: Role.TEAM_MEMBER },
  { key: 'u13', name: 'Burak Aksoy', dept: 'bt', role: Role.MANAGER },
  { key: 'u14', name: 'Can Yılmaz', dept: 'bt', role: Role.TEAM_MEMBER },
  { key: 'u15', name: 'Gizem Çelik', dept: 'bt', role: Role.TEAM_MEMBER },
  { key: 'u10', name: 'Ece Sarı', dept: 'finans', role: Role.MANAGER },
  { key: 'u9', name: 'Zeynep Şahin', dept: 'finans', role: Role.TEAM_MEMBER },
  { key: 'u6', name: 'Selin Aydın', dept: 'gm', role: Role.MANAGER },
  { key: 'u5', name: 'Deniz Acar', dept: 'gm', role: Role.TEAM_MEMBER },
  { key: 'u16', name: 'Kaan Erdem', dept: 'isgel', role: Role.MANAGER },
  { key: 'u17', name: 'Nazlı Tuna', dept: 'isgel', role: Role.TEAM_MEMBER },
  { key: 'u18', name: 'Hakan Polat', dept: 'ismuk', role: Role.MANAGER },
  { key: 'u11', name: 'Elif Arslan', dept: 'ismuk', role: Role.TEAM_MEMBER },
  { key: 'u12', name: 'Cem Öztürk', dept: 'kalite', role: Role.MANAGER },
  { key: 'u19', name: 'Seda Kurt', dept: 'kalite', role: Role.TEAM_MEMBER },
  { key: 'u20', name: 'Okan Şen', dept: 'kamu', role: Role.MANAGER },
  { key: 'u21', name: 'Pınar Ateş', dept: 'kamu', role: Role.TEAM_MEMBER },
  { key: 'u22', name: 'Leyla Güneş', dept: 'medikal', role: Role.MANAGER },
  { key: 'u23', name: 'Emre Taş', dept: 'medikal', role: Role.TEAM_MEMBER },
  { key: 'u24', name: 'Serkan Bulut', dept: 'spesifik', role: Role.MANAGER },
  { key: 'u25', name: 'İrem Koç', dept: 'spesifik', role: Role.TEAM_MEMBER },
  { key: 'u8', name: 'Murat Koç', dept: 'tedarik', role: Role.MANAGER },
  { key: 'u7', name: 'Kerem Yıldız', dept: 'tedarik', role: Role.TEAM_MEMBER },
  { key: 'u26', name: 'Tolga Kara', dept: 'temel', role: Role.MANAGER },
  { key: 'u27', name: 'Buse Er', dept: 'temel', role: Role.TEAM_MEMBER },
  { key: 'u28', name: 'Ebru Doğan', dept: 'tuketici', role: Role.MANAGER },
  { key: 'u29', name: 'Sinan Avcı', dept: 'tuketici', role: Role.TEAM_MEMBER },
  { key: 'admin', name: 'Sistem Yöneticisi', dept: null, role: Role.ADMIN },
];

/** Unvanlar — kişi aramasında görünür (gerçek kurulumda kurumsal dizinden gelir). */
export const TITLES: Record<string, string> = {
  u1: 'İK İş Ortağı', u2: 'Bordro Uzmanı', u3: 'İnsan Kaynakları Müdürü', u4: 'İşe Alım Uzmanı',
  u13: 'Bilgi Teknolojileri Müdürü', u14: 'BT Destek Uzmanı', u15: 'SAP Uygulama Uzmanı',
  u10: 'Finans Müdürü', u9: 'Muhasebe Uzmanı',
  u6: 'Genel Müdür Yardımcısı', u5: 'Yönetici Asistanı',
  u16: 'İş Geliştirme Müdürü', u17: 'Uluslararası Pazarlar Uzmanı',
  u18: 'Ticari Operasyonlar Müdürü', u11: 'Süreç Geliştirme Uzmanı',
  u12: 'Kalite Güvence Müdürü', u19: 'Kalite Güvence Uzmanı',
  u20: 'Kamu İlişkileri Müdürü', u21: 'Pazar Erişim Uzmanı',
  u22: 'Medikal Müdür', u23: 'Medikal Danışman',
  u24: 'Spesifik Tedaviler Grup Müdürü', u25: 'Ürün Müdürü',
  u8: 'Tedarik Zinciri Müdürü', u7: 'Satınalma Uzmanı',
  u26: 'Temel Tedaviler Grup Müdürü', u27: 'Marka Uzmanı',
  u28: 'Tüketici Sağlığı Grup Müdürü', u29: 'Kategori Uzmanı',
  admin: 'Sistem Yöneticisi',
};

/**
 * Bilgi Bankası örnekleri. Bağlantılar örnek alan adında (ornek.com) —
 * kurulumda ekipler kendi gerçek adreslerini girer.
 */
export interface KbSeed {
  dept: string;
  kind: 'BILGI' | 'UYGULAMA' | 'SUREC';
  title: string;
  keywords: string;
  answer: string;
  url: string | null;
  /** Maddeyi yazan (demo kullanıcı anahtarı). */
  by: string;
}

export const KB_ARTICLES: KbSeed[] = [
  { dept: 'ik', kind: 'UYGULAMA', by: 'u3', title: 'Bordro ve ücret pusulası',
    keywords: 'bordro, maaş, ücret pusulası, e-bordro, maaş bordrosu',
    answer: 'Bordronuzu ve ücret pusulalarınızı İK portalındaki Bordro ekranından görüntüleyebilirsiniz. Eksik ya da hatalı bir kalem görürseniz İnsan Kaynakları ekibine kayıt açın.',
    url: 'https://ikportal.ornek.com/bordro' },
  { dept: 'ik', kind: 'SUREC', by: 'u3', title: 'Yıllık izin talebi',
    keywords: 'izin, yıllık izin, izin bakiyesi, izin onayı, izin talebi',
    answer: 'Yıllık izninizi İK portalı > İzin Talebi ekranından oluşturun; talep yöneticinizin onayına düşer. Kalan izin bakiyeniz aynı ekranda görünür.',
    url: 'https://ikportal.ornek.com/izin' },
  { dept: 'ik', kind: 'BILGI', by: 'u3', title: 'Özel sağlık sigortasına aile bireyi ekleme',
    keywords: 'sağlık sigortası, özel sağlık, eş ekleme, çocuk ekleme, aile ekleme',
    answer: 'Eş ve çocuklarınızı her yıl ocak ayındaki yenileme döneminde ya da evlilik, doğum gibi durumlarda 30 gün içinde ekleyebilirsiniz. Nüfus kayıt örneğiyle İnsan Kaynakları ekibine başvurun.',
    url: null },
  { dept: 'bt', kind: 'UYGULAMA', by: 'u13', title: 'SAP erişimi ve yetki talebi',
    keywords: 'sap, erp, sap yetki, sap şifre, sap rol',
    answer: 'SAP’ye kurumsal giriş sayfasından tek oturumla erişebilirsiniz. Yeni rol ya da yetki için Bilgi Teknolojileri ekibine kayıt açın; yöneticinizin onayı gerekir.',
    url: 'https://sap.ornek.com' },
  { dept: 'bt', kind: 'BILGI', by: 'u13', title: 'VPN bağlantı sorunu',
    keywords: 'vpn, uzaktan bağlantı, evden bağlanamıyorum, vpn kopuyor',
    answer: 'VPN istemcisini güncel sürüme yükseltin ve kurumsal profili yeniden indirin. Sorun sürerse istemci günlüğüyle birlikte Bilgi Teknolojileri ekibine kayıt açın.',
    url: 'https://destek.ornek.com/vpn' },
  { dept: 'bt', kind: 'SUREC', by: 'u13', title: 'Şifre sıfırlama ve kilitlenen hesap',
    keywords: 'şifre, parola, hesap kilitlendi, şifremi unuttum, windows hesabı',
    answer: 'Şifrenizi self-servis şifre sıfırlama sayfasından cep telefonu doğrulamasıyla yenileyebilirsiniz. Kilitlenen hesap 15 dakika sonra kendiliğinden açılır.',
    url: 'https://sifre.ornek.com' },
  { dept: 'finans', kind: 'SUREC', by: 'u10', title: 'Masraf beyanı ve harcırah',
    keywords: 'masraf, harcırah, fatura, avans, masraf iadesi',
    answer: 'Masraflarınızı ayın son iş gününe kadar masraf sistemine fiş ya da fatura görseliyle girin; yönetici onayından sonra bir sonraki maaşla ödenir.',
    url: 'https://masraf.ornek.com' },
  { dept: 'tedarik', kind: 'UYGULAMA', by: 'u8', title: 'Satınalma talebi oluşturma',
    keywords: 'satınalma, satın alma, sipariş, tedarikçi, talep',
    answer: 'Satınalma taleplerinizi tedarik portalından oluşturun; tutar sınırına göre onay akışı kendiliğinden başlar.',
    url: 'https://tedarik.ornek.com' },
  { dept: 'kalite', kind: 'SUREC', by: 'u12', title: 'Sapma kaydı açma',
    keywords: 'sapma, deviation, gmp, kalite olayı',
    answer: 'Sapmayı tespit ettiğiniz gün kalite yönetim sisteminde kaydedin; Kalite Güvence ekibi bir iş günü içinde sınıflandırır.',
    url: 'https://kys.ornek.com' },
];

export interface Topic {
  type: 'bilgi' | 'oneri';
  titles: [string, string];
  details: [string, string];
  resolution: string;
}

/** Ünite başına kayıt sayısı — toplam 300. Gerçekçi olsun diye eşit değil. */
export const COUNTS: Record<string, number> = {
  bt: 40, ik: 40, finans: 25, tedarik: 25, ismuk: 24, kalite: 22, medikal: 20,
  kamu: 20, spesifik: 18, temel: 18, tuketici: 18, isgel: 15, gm: 15,
};

/**
 * Açıklamanın sonuna eklenen, her ünitede eşit sıklıkta geçen cümleler.
 * Gerçek kayıtlardaki "gürültüyü" taklit eder; ekip ayırt etmez.
 */
export const CONTEXT = [
  '',
  'Konu acil, desteğinizi rica ederim.',
  'Daha önce de benzer bir durum yaşamıştım.',
  'Ekipteki diğer arkadaşlar da aynı durumu yaşıyor.',
  'Geri dönüşünüzü bekliyorum.',
  'Gerekirse ek bilgi verebilirim.',
  'Teşekkürler.',
];

const t = (
  type: Topic['type'],
  titles: [string, string],
  details: [string, string],
  resolution: string,
): Topic => ({ type, titles, details, resolution });

export const TOPICS: Record<string, Topic[]> = {
  bt: [
    t('bilgi', ['VPN bağlantısı kopuyor', 'Evden VPN ile bağlanamıyorum'],
      ['Evden çalışırken VPN bağlantım birkaç dakikada bir kopuyor, kurumsal ağa erişemiyorum.',
       'VPN istemcisi kimlik doğrulama hatası veriyor, uzaktan erişim sağlanamıyor.'],
      'VPN istemcisi güncellendi, sertifika yenilendi; bağlantı stabil.'),
    t('bilgi', ['SAP yetki talebi', "SAP'de rapor ekranına erişim yetkisi"],
      ["SAP'de satın alma siparişlerini görüntüleyebilmek için rol yetkisi tanımlanmasını talep ediyorum.",
       'SAP raporlarını açarken yetkiniz yok uyarısı alıyorum, rol tanımımın kontrol edilmesini rica ederim.'],
      'Yönetici onayıyla SAP rolü atandı, yetki aktif.'),
    t('bilgi', ['Dizüstü bilgisayar çok yavaş', 'Bilgisayarım açılışta donuyor'],
      ['Dizüstü bilgisayarım son güncellemeden sonra çok yavaşladı, uygulamalar geç açılıyor.',
       'Bilgisayar açılışta mavi ekran verip yeniden başlıyor, disk dolu uyarısı da var.'],
      'Disk temizlendi, sürücüler güncellendi; cihaz yenileme listesine alındı.'),
    t('bilgi', ['Outlook e-posta senkronizasyonu', 'E-postalarım telefonda görünmüyor'],
      ["Outlook'ta gelen kutusu senkronize olmuyor, e-postalar gecikmeli düşüyor.",
       'Kurumsal e-posta hesabım mobil cihazda eşitlenmiyor, takvim davetleri görünmüyor.'],
      'Posta kutusu profili yeniden oluşturuldu, mobil cihaz yeniden kaydedildi.'),
    t('bilgi', ['Şifre sıfırlama ve hesap kilidi', 'Windows hesabım kilitlendi'],
      ['Birkaç hatalı denemeden sonra Windows hesabım kilitlendi, oturum açamıyorum.',
       'Parolamın süresi doldu, yeni parola belirlerken karmaşıklık hatası alıyorum.'],
      'Hesap kilidi kaldırıldı, parola sıfırlama bağlantısı iletildi; MFA kaydı kontrol edildi.'),
    t('bilgi', ['Yazıcı sürücüsü kurulumu', 'Kat yazıcısından çıktı alamıyorum'],
      ['Yeni kat yazıcısını bilgisayarıma tanıtamıyorum, sürücü kurulumu hata veriyor.',
       'Yazıcı kuyruğunda işler bekliyor, renkli çıktı alınamıyor.'],
      'Yazıcı sürücüsü dağıtıldı, kuyruk temizlendi.'),
    t('oneri', ['Toplantı odalarına video konferans sistemi', 'Teams toplantı odalarına kamera'],
      ['Hibrit toplantılar için toplantı odalarına Teams uyumlu kamera ve mikrofon kurulmasını öneriyorum.',
       'Uzaktan katılımcılar odadakileri duyamıyor, video konferans donanımı eklenmesini öneriyorum.'],
      'Üç toplantı odasına video konferans cihazı kuruldu.'),
    t('bilgi', ['Yazılım lisansı talebi', 'Power BI Pro lisansı ihtiyacı'],
      ['Analiz çalışmalarım için Power BI Pro lisansı tanımlanmasını talep ediyorum.',
       'Adobe Acrobat lisansımın süresi dolmuş, PDF düzenleme yapamıyorum.'],
      'Lisans havuzundan atama yapıldı, kurulum tamamlandı.'),
    t('bilgi', ['Şüpheli oltalama e-postası', 'Phishing olabilecek bir e-posta aldım'],
      ['Kargo bildirimi gibi görünen ve bağlantıya tıklamamı isteyen şüpheli bir e-posta aldım.',
       'Yöneticimin adını kullanan bir hesaptan acil ödeme isteyen e-posta geldi, sahte olabilir.'],
      'E-posta siber güvenlik ekibince incelendi, gönderen engellendi.'),
    t('oneri', ['Ortak sürücü yerine SharePoint', "Dosya paylaşımının SharePoint'e taşınması"],
      ['Ağ sürücüsündeki ortak klasörlerin sürüm takibi olan SharePoint kitaplıklarına taşınmasını öneriyorum.',
       'Aynı Excel dosyasının birden çok kopyası oluşuyor, OneDrive ve SharePoint ile birlikte çalışmayı öneriyorum.'],
      'Pilot ekip için SharePoint geçişi planlandı.'),
  ],

  ik: [
    t('bilgi', ['Yıllık izin bakiyesi', 'Kalan izin günlerim hatalı görünüyor'],
      ['İzin sisteminde yıllık izin bakiyem eksik görünüyor, devreden izinlerin eklenmesini rica ederim.',
       'Bu yıl hak ettiğim yıllık izin günü sayısını ve devreden izin bakiyemi öğrenmek istiyorum.'],
      'İzin bakiyesi kıdem bilgisine göre güncellendi.'),
    t('bilgi', ['Bordroda eksik ödeme', 'Maaş bordromda fark var'],
      ['Bu ayki bordromda fazla mesai ödemesi yer almıyor, kontrol edilmesini rica ederim.',
       'Maaş bordrosundaki kesinti kalemlerinden birini anlayamadım, açıklama bekliyorum.'],
      'Bordro kontrol edildi, fark bir sonraki maaşla ödenecek.'),
    t('bilgi', ['Özel sağlık sigortasına aile ekleme', 'Tamamlayıcı sağlık sigortası kapsamı'],
      ['Yeni doğan çocuğumun özel sağlık sigortası kapsamına eklenmesini talep ediyorum.',
       'Tamamlayıcı sağlık sigortasının diş tedavisini kapsayıp kapsamadığını öğrenmek istiyorum.'],
      'Sigorta şirketine bildirim yapıldı, poliçe güncellendi.'),
    t('bilgi', ['Liderlik gelişim programı', 'Yabancı dil eğitimi desteği'],
      ['Liderlik gelişim programına katılım koşullarını ve başvuru tarihlerini öğrenmek istiyorum.',
       'Şirketin yabancı dil kursu desteğinden yararlanmak istiyorum, başvuru süreci nedir?'],
      'Eğitim kataloğu ve başvuru formu iletildi.'),
    t('bilgi', ['Performans değerlendirme dönemi', 'Performans hedef girişi süre uzatımı'],
      ['Performans değerlendirme formunda yönetici onayı bekleyen hedeflerim var, süre uzatılabilir mi?',
       'Yıl sonu performans görüşmesinin takvimini ve değerlendirme kriterlerini öğrenmek istiyorum.'],
      'Hedef giriş süresi bir hafta uzatıldı, takvim paylaşıldı.'),
    t('bilgi', ['Personel servis güzergâhı', 'Servis saatinde değişiklik talebi'],
      ['Taşındığım için personel servis güzergâhının yeni adresime göre değiştirilmesini talep ediyorum.',
       'Akşam servisinin kalkış saati vardiya bitişine yetişmiyor.'],
      'Servis güzergâhı güncellendi, yeni durak bilgisi iletildi.'),
    t('oneri', ['Esnek çalışma saatleri', 'Hibrit çalışma gününün artırılması'],
      ['Ofise geliş saatlerinde esnek çalışma modelinin uygulanmasını öneriyorum.',
       'Haftalık uzaktan çalışma gün sayısının ekiplerin ihtiyacına göre belirlenmesini öneriyorum.'],
      'Öneri yan haklar komitesinde değerlendirmeye alındı.'),
    t('bilgi', ['Çalışma belgesi talebi', 'SGK hizmet dökümü ve çalışma belgesi'],
      ['Banka kredi başvurusu için ıslak imzalı çalışma belgesine ihtiyacım var.',
       'Vize başvurum için İngilizce çalışma belgesi ve maaş yazısı talep ediyorum.'],
      'Belge hazırlandı, imzalı nüshası iletildi.'),
    t('bilgi', ['İç ilan başvurusu', 'Açık pozisyona iç aday başvurusu'],
      ['İç ilanlarda yayınlanan pozisyona başvurmak istiyorum, mevcut yöneticimin onayı gerekiyor mu?',
       'Ekibimiz için açılan pozisyonun işe alım sürecinin hangi aşamada olduğunu öğrenmek istiyorum.'],
      'İç başvuru süreci açıklandı, başvuru alındı.'),
    t('bilgi', ['Doğum izni dönüşü', 'Babalık ve mazeret izni'],
      ['Doğum iznim bitiyor, işe dönüş tarihimi ve süt iznimi planlamak istiyorum.',
       'Babalık izni ve mazeret izni günlerinin nasıl kullanılacağını öğrenmek istiyorum.'],
      'Yasal izin hakları ve başvuru formu iletildi.'),
    t('bilgi', ['İşten ayrılış ve kıdem tazminatı', 'Emeklilik başvuru süreci'],
      ['İstifa etmeyi düşünüyorum, ihbar süresi ve kıdem tazminatı haklarımı öğrenmek istiyorum.',
       'Emeklilik başvurusu için şirketten hangi belgeleri almam gerekiyor?'],
      'Ayrılış ve emeklilik süreci açıklandı, belgeler hazırlandı.'),
    t('oneri', ['Yemek kartı limitinin güncellenmesi', 'Yemekhane menüsüne sağlıklı seçenek'],
      ['Artan fiyatlar nedeniyle yemek kartı günlük limitinin güncellenmesini öneriyorum.',
       'Yemekhane menüsüne vegan ve düşük kalorili seçenek eklenmesini öneriyorum.'],
      'Öneri yan haklar bütçesi kapsamında değerlendirildi.'),
  ],

  finans: [
    t('bilgi', ['Masraf beyanı onayı', 'Harcırah ve masraf iadesi'],
      ['Geçen ay girdiğim masraf beyanı hâlâ onay bekliyor, iade ne zaman yapılır?',
       'Yurt içi seyahat harcırahı hesaplamasında konaklama gideri eksik görünüyor.'],
      'Masraf beyanı onaylandı, ödeme bir sonraki ödeme gününde yapılacak.'),
    t('bilgi', ['Tedarikçi fatura ödemesi', 'Vadesi geçen fatura'],
      ['Tedarikçimizin vadesi geçmiş faturasının ödeme durumunu öğrenmek istiyorum.',
       'Fatura muhasebeye ulaşmış görünüyor ama ödeme listesinde yok.'],
      'Fatura onay akışı tamamlandı, ödeme planına alındı.'),
    t('bilgi', ['Kurumsal kredi kartı limiti', 'Şirket kredi kartı talebi'],
      ['Fuar katılımı için kurumsal kredi kartı limitimin geçici olarak artırılmasını talep ediyorum.',
       'Sık seyahat ettiğim için kurumsal kredi kartı tahsis edilmesini rica ederim.'],
      'Limit artışı onaylandı, banka ile güncellendi.'),
    t('bilgi', ['Bütçe revizyonu', 'Departman bütçesi aktarımı'],
      ['Bütçe kalemleri arasında aktarım yapılması gerekiyor, controlling onayı nasıl alınır?',
       'Üçüncü çeyrek bütçe revizyonu takvimini ve şablonunu öğrenmek istiyorum.'],
      'Bütçe aktarımı controlling onayıyla yapıldı.'),
    t('bilgi', ['İş avansı talebi', 'İş avansı kapama'],
      ['Saha ziyareti için iş avansı talep ediyorum, avans formu nerede?',
       'Kullandığım iş avansını faturalarla kapatmak istiyorum, belgeleri muhasebeye nasıl iletmeliyim?'],
      'Avans formu iletildi, kapama belgeleri muhasebeye işlendi.'),
    t('oneri', ['Masraf fişlerinin mobil uygulamayla girilmesi', 'Fatura onayının dijitalleşmesi'],
      ['Masraf fişlerinin fotoğrafla mobil uygulama üzerinden girilmesini öneriyorum.',
       'Kâğıt fatura onay sürecinin e-fatura ile dijital onay akışına taşınmasını öneriyorum.'],
      'Mobil masraf uygulaması pilot olarak devreye alındı.'),
    t('bilgi', ['Vergi ve stopaj sorusu', 'Serbest meslek makbuzu kesintisi'],
      ['Yurt dışından alınan danışmanlık hizmetinde stopaj oranını öğrenmek istiyorum.',
       'Konuşmacı ödemesinde serbest meslek makbuzu ve vergi kesintisinin nasıl hesaplanacağını öğrenmek istiyorum.'],
      'Vergi danışmanından alınan görüş paylaşıldı.'),
  ],

  tedarik: [
    t('bilgi', ['Ürün stok durumu', 'Depoda stok yetersiz'],
      ['Eczane siparişleri için ürün stokunun ne zaman yenileneceğini öğrenmek istiyorum.',
       'Ana depoda stok yetersiz görünüyor, sevkiyat planı nedir?'],
      'Stok planı paylaşıldı, üretim siparişi öne çekildi.'),
    t('bilgi', ['Sevkiyat gecikmesi', 'Ecza deposuna teslimat gecikti'],
      ['Ecza deposuna yapılacak sevkiyat iki gündür bekliyor, lojistik firmasından bilgi alınabilir mi?',
       'Soğuk zincir ürünlerin teslimatında gecikme yaşandı, lojistik planı kontrol edilmeli.'],
      'Lojistik firmasıyla görüşüldü, sevkiyat yeniden planlandı.'),
    t('bilgi', ['Hammadde tedarikçisi termini', 'Etken madde temininde gecikme'],
      ['Etken madde tedarikçisinden gelecek partinin teslim tarihini öğrenmek istiyorum.',
       'Alternatif hammadde tedarikçisi onay sürecinin durumunu öğrenmek istiyorum.'],
      'Tedarikçiyle termin teyit edildi, alternatif kaynak süreci başlatıldı.'),
    t('bilgi', ['Ambalaj malzemesi siparişi', 'Karton kutu ve prospektüs temini'],
      ['Yeni ambalaj tasarımı için karton kutu ve prospektüs siparişinin verilmesi gerekiyor.',
       'Blister folyo stoku azaldı, ambalaj malzemesi satın alma talebi açmak istiyorum.'],
      'Satın alma siparişi oluşturuldu, teslim tarihi bildirildi.'),
    t('bilgi', ['Talep tahmini ve üretim planı', 'Satış tahmininin üretim planlamaya aktarılması'],
      ['Önümüzdeki çeyrek için talep tahmininin üretim planına nasıl yansıtılacağını öğrenmek istiyorum.',
       'Kampanya nedeniyle artan talebin üretim planlamaya iletilmesi gerekiyor.'],
      'Talep planlama toplantısında tahmin güncellendi.'),
    t('oneri', ['Depoda karekod okutma süreci', 'Depo yönetiminde el terminali'],
      ['Depo girişlerinde ilaç takip sistemi karekodlarının el terminaliyle okutulmasını öneriyorum.',
       'Raf adresleme ve barkodlu sayım ile depo envanter farklarının azaltılmasını öneriyorum.'],
      'El terminali alımı onaylandı, pilot depo belirlendi.'),
    t('bilgi', ['Gümrük ve ithalat süreci', 'İthal parti gümrükte bekliyor'],
      ['İthal edilen partinin gümrük işlemleri tamamlanmadı, eksik evrak var mı?',
       'İthalat için gereken ön izin ve gümrük belgelerini öğrenmek istiyorum.'],
      'Gümrük müşaviriyle eksik evrak tamamlandı, parti teslim alındı.'),
  ],

  ismuk: [
    t('bilgi', ["CRM'de ziyaret kaydı", "Saha ziyaret raporları CRM'de görünmüyor"],
      ['Tıbbi mümessil ziyaret kayıtlarım CRM sisteminde görünmüyor.',
       "CRM'de hekim listesi ve hedef segmentleri güncel değil."],
      'CRM eşitleme sorunu giderildi, hedef listesi güncellendi.'),
    t('bilgi', ['Satış performans raporu', 'Bölge satış dashboard erişimi'],
      ['Bölge bazlı satış performans raporuna erişim yetkisi talep ediyorum.',
       "Aylık satış dashboard'unda pazar payı verisi güncellenmemiş."],
      'Rapor yetkisi tanımlandı, veri kaynağı yenilendi.'),
    t('oneri', ['Sipariş sürecinde süreç iyileştirme', 'Yalın süreç çalıştayı'],
      ['Sipariş-teslim sürecindeki onay adımlarının azaltılması için süreç iyileştirme çalışması öneriyorum.',
       'Ekipler arası el değiştiren işler için yalın süreç çalıştayı düzenlenmesini öneriyorum.'],
      'Süreç iyileştirme projesi portföye alındı.'),
    t('bilgi', ['Saha ekibi bölge ataması', 'Tıbbi mümessil bölge değişikliği'],
      ['Saha satış ekibinin bölge atamalarında yapılan değişikliğin sisteme yansıtılması gerekiyor.',
       'Yeni katılan tıbbi mümessilin bölge ve brick tanımlarının yapılmasını talep ediyorum.'],
      'Bölge ataması ticari operasyonlarca güncellendi.'),
    t('bilgi', ['Satış primi hesaplaması', 'Prim hedef gerçekleşme oranı hatalı'],
      ['Satış ekibi prim hesaplamasında hedef gerçekleşme oranları hatalı görünüyor.',
       'Çeyreklik teşvik ve prim sistemi kurallarını ve hesaplama yöntemini öğrenmek istiyorum.'],
      'Prim hesaplaması kontrol edildi, düzeltme yapıldı.'),
    t('oneri', ['Ticari analitik için tek veri kaynağı', 'Satış verilerinin tek panelde toplanması'],
      ['Farklı Excel dosyalarındaki satış verilerinin tek bir ticari analitik panelinde toplanmasını öneriyorum.',
       "Eczane çıkış verisi ile iç satış verisinin aynı dashboard'da birleştirilmesini öneriyorum."],
      'Ticari analitik paneli yol haritasına eklendi.'),
  ],

  kalite: [
    t('bilgi', ['Ürün şikayeti kaydı', 'Eczaneden gelen ürün şikayeti'],
      ['Eczaneden gelen ürün şikayetini kalite sistemine nasıl kaydedeceğimi öğrenmek istiyorum.',
       'Hasta tabletlerde renk farkı bildirdi, ürün şikayetinin incelenmesi gerekiyor.'],
      'Şikayet kalite sistemine kaydedildi, numune incelemesi başlatıldı.'),
    t('bilgi', ['Sapma kaydı ve CAPA', 'Üretimde sapma bildirimi'],
      ['Üretim hattında gözlenen sapmanın kayıt altına alınması ve CAPA açılması gerekiyor.',
       'Açık düzeltici ve önleyici faaliyetlerin termin takibini öğrenmek istiyorum.'],
      'Sapma kaydı açıldı, kök neden analizi planlandı.'),
    t('bilgi', ['Seri serbest bırakma', 'Kalite onayı bekleyen parti'],
      ['Serbest bırakılmayı bekleyen partinin analiz sonuçları ne zaman tamamlanacak?',
       'Karantinadaki seri için kalite onay sürecinin durumunu öğrenmek istiyorum.'],
      'Analiz sonuçları onaylandı, seri serbest bırakıldı.'),
    t('bilgi', ['GMP denetimine hazırlık', 'Bakanlık denetimi dokümantasyonu'],
      ['Yaklaşan GMP denetimi için hazırlanması gereken dokümanların listesini öğrenmek istiyorum.',
       'Denetim öncesi standart çalışma prosedürlerinin güncel olup olmadığının kontrolü gerekiyor.'],
      'Denetim hazırlık listesi paylaşıldı, SOP gözden geçirmesi planlandı.'),
    t('oneri', ['Kalite dokümanlarının elektronik yönetimi', 'SOP eğitim takibinin sisteme alınması'],
      ['Standart çalışma prosedürlerinin elektronik doküman yönetim sisteminde onaylanmasını öneriyorum.',
       'SOP okuma ve eğitim kayıtlarının kâğıt yerine sistem üzerinden takip edilmesini öneriyorum.'],
      'Elektronik doküman yönetimi projesi başlatıldı.'),
    t('bilgi', ['Validasyon ve kalibrasyon', 'Laboratuvar cihazı kalibrasyon süresi'],
      ['Laboratuvar cihazının kalibrasyon süresi dolmak üzere, planlama yapılmalı.',
       'Yeni ekipmanın kalifikasyon ve validasyon protokolünün onayı gerekiyor.'],
      'Kalibrasyon planlandı, protokol onaylandı.'),
  ],

  medikal: [
    t('bilgi', ['Tıbbi bilgi talebi', 'Hekimden gelen bilimsel soru'],
      ['Bir hekim ürünümüzün böbrek yetmezliğinde doz ayarlaması hakkında bilimsel bilgi talep etti.',
       'Eczacıdan gelen ilaç etkileşimi sorusu için tıbbi bilgi yanıtı hazırlanması gerekiyor.'],
      'Tıbbi bilgi yanıtı literatürle hazırlanıp iletildi.'),
    t('bilgi', ['Advers etki bildirimi', 'Farmakovijilans yan etki bildirimi'],
      ['Hasta yakınından gelen yan etki bilgisini farmakovijilans birimine nasıl iletmeliyim?',
       'Saha ziyaretinde hekim bir advers olay bildirdi, raporlama süresi nedir?'],
      'Bildirim farmakovijilans sistemine girildi, yasal süre içinde raporlandı.'),
    t('bilgi', ['Gözlemsel çalışma onayı', 'Klinik araştırma veri toplama'],
      ['Yeni gözlemsel çalışma için etik kurul başvuru sürecini öğrenmek istiyorum.',
       'Klinik araştırma merkezlerinden gelen veri toplama formlarının durumu nedir?'],
      'Çalışma protokolü medikal kurulda değerlendirildi.'),
    t('bilgi', ['Kongre sempozyumu medikal onayı', 'Hekim eğitim toplantısı içeriği'],
      ['Kongre sempozyumu için konuşmacı hekim sunumunun medikal onayı gerekiyor.',
       'Hekimlere yönelik eğitim toplantısında kullanılacak bilimsel içeriğin gözden geçirilmesini rica ederim.'],
      'Sunum medikal onaydan geçti.'),
    t('oneri', ['Medikal literatür bülteni', 'Mümessillere bilimsel eğitim'],
      ['Terapötik alanlardaki güncel bilimsel literatürün aylık bültenle paylaşılmasını öneriyorum.',
       'Tıbbi mümessillere yeni endikasyonlar hakkında bilimsel eğitim verilmesini öneriyorum.'],
      'Aylık literatür bülteni başlatıldı.'),
  ],

  kamu: [
    t('bilgi', ['SGK geri ödeme listesi', 'Ürünün geri ödeme kapsamına alınması'],
      ['Yeni ürünün SGK geri ödeme listesine alınması için başvuru durumunu öğrenmek istiyorum.',
       'Sağlık uygulama tebliğindeki ödeme kuralı değişikliğinin ürünlerimize etkisi nedir?'],
      'Geri ödeme başvuru dosyası güncellendi, takip ediliyor.'),
    t('bilgi', ['İlaç fiyat kararnamesi', 'Beşeri ilaç fiyat güncellemesi'],
      ['Yeni fiyat kararnamesi sonrası ürün fiyatlarının ne zaman güncelleneceğini öğrenmek istiyorum.',
       'Avro değeri güncellemesinin beşeri ilaç fiyatlarına yansıması hakkında bilgi rica ederim.'],
      'Fiyat değişikliği listesi ilgili ekiplere iletildi.'),
    t('bilgi', ['Kamu hastanesi ihalesi', 'Şehir hastanesi ilaç alım ihalesi'],
      ['Şehir hastanesinin ilaç alım ihalesine katılım için gereken belgeleri öğrenmek istiyorum.',
       'İhale şartnamesindeki ürün özelliklerine itiraz süreci nasıl işliyor?'],
      'İhale dosyası hazırlandı, teklif zamanında verildi.'),
    t('bilgi', ['Sağlık Bakanlığı görüşmesi', 'TİTCK resmi yazı yanıtı'],
      ['Sağlık Bakanlığı ile yapılacak toplantı için pozisyon belgesi hazırlanması gerekiyor.',
       "TİTCK'dan gelen resmi yazının yanıt süresini ve sorumlusunu öğrenmek istiyorum."],
      'Pozisyon belgesi hazırlandı, resmi yazı yanıtlandı.'),
    t('bilgi', ['Reçete ve rapor koşulu değişikliği', 'İlacın ödeme kapsamındaki rapor şartı'],
      ['Ürünümüzün reçetelenmesi için gereken uzman hekim raporu koşulu tebliğde değişti mi?',
       'Eczanede ödenmeyen reçeteler için geri ödeme kurumuyla görüşülmesi gerekiyor.'],
      'Tebliğ değişikliği incelendi, saha ekiplerine bilgi notu gönderildi.'),
    t('oneri', ['Sağlık ekonomisi çalışması', 'Bütçe etki analizi şablonu'],
      ['Geri ödeme başvurularını desteklemek için sağlık ekonomisi ve maliyet etkililik çalışması yapılmasını öneriyorum.',
       'Pazar erişim dosyalarındaki bütçe etki analizlerinin standart bir şablonla hazırlanmasını öneriyorum.'],
      'Sağlık ekonomisi çalışması için danışman firma ile görüşüldü.'),
  ],

  spesifik: [
    t('bilgi', ['Onkoloji ürünü hastane listesine giriş', 'Onkoloji kliniğinden ürün talebi'],
      ['Onkoloji ürünümüzün üniversite hastanesinin ilaç listesine alınması için başvuru gerekiyor.',
       'Onkoloji kliniğinden gelen hasta erişim programı talebini değerlendirmek istiyorum.'],
      'Hastane eczacılığı ile görüşüldü, başvuru yapıldı.'),
    t('bilgi', ['Nadir hastalık hasta destek programı', 'Yetim ilaç isimli hasta başvurusu'],
      ['Nadir hastalık tanılı hastalar için hasta destek programına başvuru sürecini öğrenmek istiyorum.',
       'Yurt dışından getirilen yetim ilaç için isimli hasta başvurusunun durumu nedir?'],
      'Hasta destek programı başvurusu tamamlandı.'),
    t('bilgi', ['Biyoteknolojik ürün lansmanı', 'Biyobenzer ürün tanıtımı'],
      ['Biyoteknolojik ürünün lansman planı ve uzman hekim toplantı takvimini öğrenmek istiyorum.',
       'Biyobenzer ürün için hastane satış ekibine tanıtım materyali hazırlanması gerekiyor.'],
      'Lansman planı paylaşıldı, materyal hazırlandı.'),
    t('bilgi', ['Hematoloji uzmanı ziyaret planı', 'Romatoloji kliniği biyolojik tedavi verisi'],
      ['Hematoloji ve onkoloji uzmanlarına yönelik ziyaret planının güncellenmesi gerekiyor.',
       'Romatoloji kliniklerindeki biyolojik tedavi kullanım verisini öğrenmek istiyorum.'],
      'Uzman hekim segmentasyonu güncellendi, ziyaret planı onaylandı.'),
    t('oneri', ['Hastane eczacılarına saklama eğitimi', 'Onkoloji hemşirelerine infüzyon eğitimi'],
      ['Hastane eczacılarına biyoteknolojik ürünlerin soğuk saklama koşulları hakkında eğitim verilmesini öneriyorum.',
       'İnfüzyon ürünlerinin hazırlanması için onkoloji hemşirelerine uygulama eğitimi öneriyorum.'],
      'Eğitim programı medikal ekiple planlandı.'),
  ],

  temel: [
    t('bilgi', ['Antibiyotik ürün tanıtım materyali', 'Pratisyen hekim broşürü'],
      ['Antibiyotik ürünümüz için pratisyen hekimlere yönelik yeni tanıtım broşürü gerekiyor.',
       'Ağrı kesici ürün grubunun pratisyen hekim tanıtım materyallerinin güncellenmesi gerekiyor.'],
      'Tanıtım materyali onaylanıp sahaya dağıtıldı.'),
    t('bilgi', ['Dermokozmetik eczane kampanyası', 'Güneş koruyucu ürün raf düzeni'],
      ['Dermokozmetik cilt bakım ürünleri için eczane kampanya koşullarını öğrenmek istiyorum.',
       'Eczanelerde güneş koruyucu ürünlerimizin raf düzeni ve görünürlüğü hakkında bilgi rica ederim.'],
      'Kampanya koşulları eczane ekibine iletildi.'),
    t('bilgi', ['Kardiyoloji ürünü pazar payı', 'Kronik tedavi portföyünde eşdeğer rekabeti'],
      ['Kardiyoloji ve diyabet portföyündeki ürünlerin pazar payı gelişimini öğrenmek istiyorum.',
       'Kronik hastalık ürünlerinde eşdeğer ilaç rekabetine karşı planımız nedir?'],
      'Portföy analizi paylaşıldı.'),
    t('bilgi', ['Eczacı eğitim toplantısı', 'Hedef eczane listesi güncellemesi'],
      ['Bölge eczacılarına yönelik kişisel bakım ürünleri eğitim toplantısı düzenlemek istiyorum.',
       'Eczane ziyaret sıklığı ve hedef eczane listesinin güncellenmesi gerekiyor.'],
      'Eczacı eğitimi takvime alındı.'),
    t('oneri', ['Bebek bakım ürünlerinde pompalı ambalaj', 'Parfümsüz şampuan varyantı'],
      ['Bebek bakım ürünlerinde kullanımı kolay pompalı şişe öneriyorum.',
       'Kişisel bakım hattına hassas ciltler için parfümsüz şampuan varyantı eklenmesini öneriyorum.'],
      'Öneri ürün geliştirme komitesine iletildi.'),
  ],

  tuketici: [
    t('bilgi', ['Vitamin ürünü dijital kampanyası', 'Sosyal medya reklam bütçesi'],
      ['Vitamin ve takviye ürünlerimiz için sosyal medya reklam kampanyasının bütçesini öğrenmek istiyorum.',
       'Dijital pazarlama ajansıyla hazırlanan kampanya görsellerinin onay durumu nedir?'],
      'Kampanya planı ve bütçe onaylandı.'),
    t('bilgi', ['Gıda takviyesi etiket onayı', 'Takviye ürün sağlık beyanı'],
      ['Yeni gıda takviyesi ürününün etiket ve beyan metinlerinin mevzuata uygunluğunun kontrolü gerekiyor.',
       'Takviye ürünün sağlık beyanı ifadesinin kullanılıp kullanılamayacağını öğrenmek istiyorum.'],
      'Etiket metni mevzuat açısından düzeltildi.'),
    t('bilgi', ['Zincir marketlerde ürün listeleme', 'Kozmetik perakende zincirinde listeleme'],
      ['Reçetesiz ürünümüzün zincir marketlerde listelenmesi için gerekli koşulları öğrenmek istiyorum.',
       'Kozmetik perakende zincirindeki ürün listeleme ve raf bedeli görüşmesi hakkında bilgi rica ederim.'],
      'Perakende listeleme görüşmesi tamamlandı.'),
    t('bilgi', ['Marka bilinirlik araştırması', 'Tüketici odak grup sonuçları'],
      ['Reçetesiz markamızın bilinirlik araştırması sonuçlarını öğrenmek istiyorum.',
       'Tüketici odak grup çalışmasının raporunu ne zaman alabiliriz?'],
      'Araştırma raporu marka ekibiyle paylaşıldı.'),
    t('oneri', ['E-ticaret kanalında resmi mağaza', 'Marka web sitesine sadakat programı'],
      ['Reçetesiz ürünlerimizin e-ticaret platformlarında resmi mağaza ile satılmasını öneriyorum.',
       'Takviye ürünleri için marka web sitesine tüketici sadakat programı eklenmesini öneriyorum.'],
      'E-ticaret kanal stratejisi değerlendirmeye alındı.'),
  ],

  isgel: [
    t('bilgi', ['Ürün lisanslama teklifi', 'Lisans anlaşması gizlilik sözleşmesi'],
      ['Yabancı bir firmadan gelen ürün lisanslama teklifinin değerlendirme sürecini öğrenmek istiyorum.',
       'Lisans anlaşması görüşmesi için gizlilik sözleşmesi taslağının hazırlanması gerekiyor.'],
      'Teklif iş geliştirme komitesine sunuldu, gizlilik sözleşmesi imzalandı.'),
    t('bilgi', ['İhracat pazarına ürün kaydı', 'Yurt dışı ruhsat dosyası'],
      ['Orta Asya pazarına ihracat için ürün kayıt dosyasının hazırlanma durumu nedir?',
       'Körfez ülkelerine ihracat için gereken ruhsat dokümanlarını öğrenmek istiyorum.'],
      'Kayıt dosyası tamamlandı, yerel otoriteye sunuldu.'),
    t('bilgi', ['Uluslararası distribütör siparişi', 'Yurt dışı iş ortağının satış tahmini'],
      ['Uluslararası distribütörümüzün sipariş ve proforma fatura talebini nasıl iletmeliyim?',
       'Yurt dışı iş ortağının pazarlama planı ve satış tahminini öğrenmek istiyorum.'],
      'Distribütör talebi uluslararası pazarlar ekibince karşılandı.'),
    t('oneri', ['Yeni pazarlara giriş stratejisi', 'Portföy genişletme için iş birliği'],
      ['Kuzey Afrika pazarına giriş için yerel bir iş ortağıyla ortaklık modelini öneriyorum.',
       'Portföyü genişletmek için girişimlerle lisans ve ortak geliştirme iş birliği öneriyorum.'],
      'Öneri strateji çalışmasına dahil edildi.'),
  ],

  gm: [
    t('bilgi', ['Şirket stratejisi sunumu', 'Yıllık hedeflerin çalışanlarla paylaşılması'],
      ['Yeni yılın şirket stratejisi ve öncelikli hedeflerinin çalışanlarla ne zaman paylaşılacağını öğrenmek istiyorum.',
       'Genel müdürün çeyrek değerlendirme toplantısı sunumuna nereden ulaşabilirim?'],
      'Strateji sunumu çalışan toplantısında paylaşıldı.'),
    t('bilgi', ['Yönetim kurulu gündemi', 'İcra kurulu karar takibi'],
      ['Yönetim kuruluna sunulacak proje için gündem başvurusunun son tarihini öğrenmek istiyorum.',
       'İcra kurulunda alınan kararın ilgili ekiplere iletilme durumu nedir?'],
      'Gündem takvimi paylaşıldı, karar ilgililere iletildi.'),
    t('oneri', ['Sürdürülebilirlik hedefleri', 'Karbon ayak izinin azaltılması'],
      ['Şirketin sürdürülebilirlik raporunda karbon ayak izi hedeflerinin açıklanmasını öneriyorum.',
       'Tesislerde yenilenebilir enerji kullanımını artıracak bir sürdürülebilirlik programı öneriyorum.'],
      'Öneri sürdürülebilirlik komitesine iletildi.'),
    t('oneri', ['Genel müdürle çalışan buluşması', 'Üst yönetim açık kapı toplantıları'],
      ['Genel müdürle çalışanların düzenli soru-cevap buluşmaları yapılmasını öneriyorum.',
       'Üst yönetimin farklı lokasyonlarda açık kapı toplantıları düzenlemesini öneriyorum.'],
      'Çeyreklik çalışan buluşmaları takvime alındı.'),
  ],
};
